### ISSUE TITLE
npm publish?

### ISSUE THREAD

**Issue by robert-chiniquy** [mikeal/requestdb#1]
Is 0.1.1 on npm? Looking here I only see 0.1.0 published: https://www.npmjs.org/package/requestdb. Somehow Max is using it anyway in https://github.com/maxogden/open-prs/blob/master/package.json#L12, so I'm not sure what I'm missing.

Thanks!

**Comment by finnp** [comment]
I think 0.1.1 was skipped now. But I just published `0.1.2`.

**Comment by robert-chiniquy** [comment]
Thanks!
